import { EventEmitter, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { Highlightable } from '@angular/cdk/a11y';
import { Subject } from 'rxjs';
import { ContextMenuItem } from './context-menu.model';
import { DropdownComponent } from './dropdown.component';
import { PopupService } from '../popup/popup.service';
import { Icon } from '../common/utils';
export declare class DropdownItemComponent implements Highlightable, OnInit, OnDestroy {
    private service;
    disabled?: boolean | undefined;
    id?: string;
    tooltip?: string;
    set icon(value: string | Icon);
    set smallIcon(value: any);
    isSmallIcon: boolean;
    set iconOnRight(value: any);
    isIconOnRight: boolean;
    shortcut?: string;
    checkboxMode: boolean;
    isSelected: boolean;
    mode: 'default' | 'primary' | 'secondary' | 'destructive';
    isDisabled: boolean;
    hasSeparator: boolean;
    subLevelItems?: ContextMenuItem[];
    subLabel?: string;
    onClick: EventEmitter<MouseEvent>;
    onEnter: EventEmitter<KeyboardEvent>;
    onSelection: EventEmitter<boolean>;
    onSubMenuSelection: EventEmitter<ContextMenuItem>;
    listItem?: ElementRef;
    subMenu?: DropdownComponent;
    _iconName: string;
    _icon?: Icon;
    subMenuOpen: boolean;
    terminator: Subject<void>;
    constructor(service: PopupService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    pressEnter(event: KeyboardEvent): void;
    pressSpace(event: KeyboardEvent): void;
    click(event: MouseEvent): void;
    clickSubMenu(event: MouseEvent): void;
    select(event: boolean): void;
    setActiveStyles(): void;
    scrollIntoView(): void;
    setInactiveStyles(): void;
    selectSubMenu(item: ContextMenuItem): void;
}
