language: node_js
node_js:
- 10.15.0
cache:
  directories:
    - node_modules
dist: trusty
install:
  - npm install
script:
  - npm test
  - npm build
notifications:
  email:
  - ebrehault@gmail.com
# deploy:
#   on:
#     branch: master
#     condition: -z $(git tag --points-at $TRAVIS_COMMIT)
#     provider: script
#     script: $TRAVIS_BUILD_DIR/travis_release.sh