language: node_js
node_js:
- 10.15.0
cache:
  directories:
    - node_modules
dist: trusty
install:
  - npm install
script:
  - npm test
  - npm build
notifications:
  email:
  - ebrehault@gmail.com
before_deploy:
  - export PACKAGE_VERSION=$(cat ./projects/pastanaga/package.json | grep version  | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')
  - git tag $PACKAGE_VERSION
deploy:
  on:
    tags: true