import { ChangeDetectorRef, ElementRef, EventEmitter, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { SidebarService } from './sidebar.service';
export declare class SidebarComponent implements OnInit, OnDestroy {
    private elementRef;
    private sidebarService;
    private renderer;
    private cdr;
    name?: string;
    position: 'left' | 'right';
    set unfoldOnHover(value: boolean);
    get unfoldOnHover(): boolean;
    private _unfoldOnHover;
    set noBackdrop(value: boolean);
    get noBackdrop(): boolean;
    private _noBackdrop;
    set foldedWidth(value: number);
    get foldedWidth(): number;
    private _foldedWidth;
    set folded(value: boolean);
    get folded(): boolean;
    private _folded;
    set lockedOpen(value: boolean);
    get lockedOpen(): boolean;
    _lockedOpen: boolean;
    openedChanged: EventEmitter<boolean>;
    foldedChanged: EventEmitter<boolean>;
    isOpen: boolean;
    animationsEnabled: boolean;
    private backdrop;
    constructor(elementRef: ElementRef, sidebarService: SidebarService, renderer: Renderer2, cdr: ChangeDetectorRef);
    ngOnInit(): void;
    ngOnDestroy(): void;
    onMouseEnter(): void;
    onMouseLeave(): void;
    toggleOpen(open?: boolean): void;
    open(): void;
    close(): void;
    toggleFold(): void;
    private setupPosition;
    private enableAnimations;
    private showBackdrop;
    private hideBackdrop;
    private markForCheck;
}
